117 come up with resulttextzabo
gsainfoteam/ziggle-fe pull request #121
Opened 2023-11-08 13:40 UTC by MiRoro2

기존(Next migration 전)에 있던 컴포넌트 이름은 SearchResult 였으나, ImageZabo와 TextZabo를 합친 @2paperstar 의 컨벤션을 따르기 위해 ResultZabo로 컴포넌트 이름을 바꿨습니다.

ResultZabo 안에 들어가셔서 ResultTextZabo를 보시면 제가 마이그레이션 해놓을 것을 보실 수 있습니다.

본 migration뿐만 아니라 다른 잡다한 것들도 업데이트해놓았습니다. 살펴봐주세요

2023-11-08 15:12 UTC, dohyun-ko approved these changes
수고 많으셨습니다

2023-11-08 23:38 UTC, 2paperstar commented on src/app/components/molecules/HighlightedText/HighlightedText.tsx
css 적용이라하면 어떤 일들이 있을까요

2023-11-08 23:47 UTC, 2paperstar requested changes

2023-11-08 23:47 UTC, 2paperstar commented on src/app/components/templates/ResultZabo/ResultTextZabo.tsx
> +          {!body && <Trans t={t} i18nKey="zabo.noContent" />}
```suggestion
          {body ?? t('zabo.noContent')}
```
```suggestion
          {body || t('zabo.noContent')}
```
둘 중에 적절한거 쓰면 될 듯 해요

2023-11-08 23:47 UTC, 2paperstar commented on src/app/components/templates/ResultZabo/ResultTextZabo.tsx
> +          {!body && <Trans t={t} i18nKey="zabo.noContent" />}
\+ Trans 컴포넌트는 [interpolation](https://www.i18next.com/translation-function/interpolation)을 써야할 때만 쓰면 됩니당

2023-11-08 23:47 UTC, 2paperstar commented on src/app/components/templates/ResultZabo/ResultTextZabo.tsx
> +        'bg-white dark:bg-neutral-900'
```suggestion
        'flex flex-col justify-between gap-2.5 p-5 ' +
        'w-full box-border overflow-hidden rounded border cursor-pointer border-secondayText ' +
        'bg-white dark:bg-neutral-900'
```

2023-11-08 23:47 UTC, 2paperstar commented on src/app/components/templates/ResultZabo/ResultTextZabo.tsx
> +              {'#' + tag}
```suggestion
              {`#${tag}`}
```

2023-11-09 00:00 UTC, MiRoro2 commented on src/app/components/molecules/HighlightedText/HighlightedText.tsx
div태그로 감싸서 주면 될듯합니다
다른 문자들도 다 그렇게 되어있어서 저도 그냥 따로 text props같은 걸 넘겨준다거나 그런건 안했어용

2023-11-09 00:01 UTC, 2paperstar commented on src/app/components/molecules/HighlightedText/HighlightedText.tsx
아 그러면 되겠네요
그런데 만약에 하이라이트 될 색상을 바꿔야 할 경우라면 어떻게 하죠?

2023-11-09 00:02 UTC, MiRoro2 commented on src/app/components/templates/ResultZabo/ResultTextZabo.tsx
> +        'bg-white dark:bg-neutral-900'
이거 알아서 + 로 분리시켜주거나 ' '안에 스페이스 넣어주는거 없나요 ㅠㅠ 불편

2023-11-09 00:12 UTC, 2paperstar commented on src/app/components/templates/ResultZabo/ResultTextZabo.tsx
> +        'bg-white dark:bg-neutral-900'
https://github.com/gsainfoteam/ziggle-fe/blob/97b965aa22c83b31e9d418014527de2c43c6fb46/src/app/%5Blng%5D/notice/%5Bid%5D/Content.tsx#L9-L18

이런걸 사용했었긴 합니당,,

2023-11-09 00:22 UTC, 2paperstar approved these changes
LGTM 👍

2023-11-09 00:22 UTC, 2paperstar approved these changes
LGTM 👍

2023-11-09 02:44 UTC, merged