[feature] mypage ui nextjs migration
gsainfoteam/ziggle-fe pull request #124
Opened 2023-11-14 10:11 UTC by Shimsuyeon

껍데기만 만들 때 파라미터 처리를 어디까지 해야할지 모르겠어서
일단 기존 react에 있던 article props들 다 가져와서 파일 맨 위에 주석 처리 해놨고,

article parameter는 화면에 당장 표시되는 제목, 생성일만 넣어놨습니다.

바로 실제 데이터로 연결하는 것 같아서 목업데이터 따로 파일 안빼고 그냥 파라미터로 바로 집어넣었습니다.

리뷰 건 분들이 봐주시고 문제 있으면 핃백 해주시고
다 끝나면 익준씨가 회의록에 써진대로 <mypage 실제 데이터 api 연결> 봐주시면 감사하겠습니다

2023-11-14 10:55 UTC, 2paperstar requested changes
사용하고 계신 에디터에서 자동 포매팅이 제대로 안 되는건가요? 거의 모든 파일에서 인덴트가 이상해요

2023-11-14 10:55 UTC, 2paperstar commented on src/app/[lng]/mypage/MypageProfile.tsx
> +  const colorClass = color ? `text-${color}` : "text-gray-400";
이렇게 동적으로 style 주면 안 돼요. 색깔을 지정해야 한다면 style 프롭을 사용하거나 위쪽 컴포넌트에서 색을 직접 내려주는 방식을 사용해주세요.

2023-11-14 10:55 UTC, 2paperstar commented on src/app/[lng]/mypage/MypageProfile.tsx
> +  const sizeClass = size ? size : "h-6 w-6";
```suggestion
  const sizeClass = size ?? "h-6 w-6";
```

2023-11-14 10:55 UTC, 2paperstar commented on src/app/[lng]/mypage/MypageProfile.tsx
> +    </svg>
svg는 이렇게 직접 인라인에 넣지말고 svgr 사용해서 임포트한 뒤 사용해주세요. (svg파일을 직접 임포트하는 다른 파일을 참고해주시면 될 것 같아요)

2023-11-14 10:55 UTC, 2paperstar commented on src/app/[lng]/mypage/MypageProfile.tsx
> +    <div className="text-regular m-5 border-b border-gray-500 w-50 text-secondayText">
이전에도 이렇게 구현되어 있었나요? text underline을 text decoration으로 구현한게 아니네요?

2023-11-14 10:55 UTC, 2paperstar commented on src/app/[lng]/mypage/MypageProfile.tsx
> +export default async function MypageProfile({ name, id, phone, email, logout='', quit=''}: MypageProfileProps)
i18n은 i18next을 바로 사용해주세요 (프롭으로 i18next 변환된 값을 전달받지 말아주세요)

2023-11-14 10:55 UTC, 2paperstar commented on src/app/[lng]/mypage/MypageProfile.tsx
> +              </div>
UnderLinedText는 따로 추상화 레벨을 나누어서 표현했는데, 여기는 별도로 분리하지 않았네요? (margin bottom 값이 달라서 그러신걸까요..?)
저는 UnderLinedText도 따로 나누지 말고 MypageProfile 컴포넌트에서 바로 인라인에 넣으면 더 좋을 것 같아요.

[tailwind 문서의 reusing styles](https://tailwindcss.com/docs/reusing-styles)을 참고해주세요.

2023-11-14 10:55 UTC, 2paperstar commented on src/app/[lng]/mypage/MypageTable.tsx
> +        {articles.length > 0 &&
불필요한 조건입니다 (react에서 빈배열을 주면 그냥 렌더링하지 않음)

2023-11-14 10:55 UTC, 2paperstar commented on src/app/[lng]/mypage/MypageTable.tsx
> +                className={`flex h-[70px] ${underLine} items-center flex-row justify-between bg-colorless rounded-bl-${borderBottomRadius} rounded-br-${borderBottomRadius}`}
bl-${borderBottomRadius} 처럼 동적으로 클래스 이름을 주지 마세요
https://tailwindcss.com/docs/content-configuration#dynamic-class-names

2023-11-14 15:26 UTC, Shimsuyeon commented on src/app/[lng]/mypage/MypageProfile.tsx
> +    <div className="text-regular m-5 border-b border-gray-500 w-50 text-secondayText">
underline component로 분리되어 있던데요

2023-11-14 15:30 UTC, Shimsuyeon commented on src/app/[lng]/mypage/MypageProfile.tsx
> +export default async function MypageProfile({ name, id, phone, email, logout='', quit=''}: MypageProfileProps)
이게 아까 dm으로 코드 보내면서 물어본 그 문제입니다

component 파일 자체에서 translation 불러와서 하려고 했는데 해결이 아무리 해도 안돼서 저 방법을 쓴 겁니다

해결 할 수 있는 방법이 있다면 제안 부탁드립니다
제 선에서는 더 이상 방법을 못찾겠습니다

2023-11-14 15:32 UTC, Shimsuyeon commented on src/app/[lng]/mypage/MypageProfile.tsx
> +              </div>
frontend에서 보여지는 모양 문제로 그런겁니다
이건 처음에 border-b 넣었을 때 문제 없어서 사용한거고

underline component가 따로 분리되어 있는 건 이전 코드에서 누군가 그렇게 작성해놔서 따라간겁니다 (제가 만들 땐 그런 부분이 없었음)

2023-11-15 00:11 UTC, 2paperstar commented on src/app/[lng]/mypage/MypageProfile.tsx
> +    return (
```suggestion
export default async function MypageProfile({ name, id, phone, email, lng }: MypageProfileProps & {lng: Locale})

{
    const {t} = await useTranslation(lng, 'translation');
    return (
```

2023-11-16 16:14 UTC, 2paperstar approved these changes

2023-11-17 12:20 UTC, MiRoro2 commented
마이페이지 다크모드 예쁘네요..!!

2023-11-17 14:44 UTC, 2paperstar commented on src/app/[lng]/mypage/MypageSeperate.tsx
> +    <div className="pl-40 pt-40 m-20">
아마 기존에 그렇게 되어 있던게 아닐까요? 제가 추가한 라인이 아닙니다
cc. @Shimsuyeon

2023-11-18 14:38 UTC, Shimsuyeon commented on src/app/[lng]/mypage/MypageSeperate.tsx
> +    <div className="pl-40 pt-40 m-20">
화면이 이전 ver mypage랑 최대한 비슷하게 나오도록 이것저것 조정하면서 작성한 부분인 것 같습니다
그리고 저 부분이 mypage에서 유저 정보 표시 부분과 게시글 리스트 테이블 부분 사이를 나누는 세로선 부분인데
그 선 주변으로 여백을 두기 위해서 마진이랑 패딩을 뒀었습니다

이 부분은 제가 테일윈드 사용 숙지 미숙으로 실수한 것일수도 있어서 코드에 문제가 된다면 지우셔도 됩니다

2023-11-18 14:39 UTC, Shimsuyeon commented
> 사용하고 계신 에디터에서 자동 포매팅이 제대로 안 되는건가요? 거의 모든 파일에서 인덴트가 이상해요

네 저 prettier 적용이 안되더라구요...

2023-11-18 15:59 UTC, merged