Search page migration
gsainfoteam/ziggle-fe pull request #126
Opened 2023-11-15 11:29 UTC by dohyun-ko

2023-11-15 14:19 UTC, 2paperstar requested changes

2023-11-15 14:19 UTC, 2paperstar commented on src/app/[lng]/search/page.tsx
> +        <div className={'flex justify-center'}>
```suggestion
        <div className="flex justify-center">
```
이런식으로 바꿔주세욥

2023-11-15 14:19 UTC, 2paperstar commented on src/app/[lng]/search/page.tsx
> +        {data && data.list.length > 0 && (
```suggestion
        {data?.list.length && (
```

2023-11-15 14:19 UTC, 2paperstar commented on src/app/components/molecules/searchTagSelect/SearchTagSelect.tsx
> +          {'🎯 모집'}
얘도 translation.json에 넣어주세요

2023-11-15 14:19 UTC, 2paperstar commented on src/app/components/templates/ResultZabo/ResultImageZabo.tsx
> +          // isHover={false}
코멘트 지워요

2023-11-15 14:19 UTC, 2paperstar commented on src/app/components/templates/ResultZabo/ResultImageZabo.tsx
> +              조회수 {views}
i18next

2023-11-18 05:40 UTC, MiRoro2 commented
<img width="774" alt="스크린샷 2023-11-18 오후 2 40 06" src="https://github.com/gsainfoteam/ziggle-fe/assets/57053429/b7535364-ca3d-4950-bf91-27f71282b320">
왜 요럴까요.. 고쳐봅시다

2023-11-18 14:06 UTC, 2paperstar approved these changes

2023-11-18 14:25 UTC, merged