added locale switching button & english logo on navbar
gsainfoteam/ziggle-fe pull request #136
Opened 2023-11-17 13:26 UTC by MiRoro2

2023-11-17 15:29 UTC, 2paperstar requested changes
다른 언어를 지원할 수도 있다는 가정하에 영어를 기본언어로 하는 구조로 가면 좋겠습니다

2023-11-17 15:29 UTC, 2paperstar commented on src/app/components/templates/Navbar/Navbar.tsx
> +              )}
기본 언어가 english이고 korean이 특수한 형태로 가는게 좋을 것 같아요
```suggestion
              {lng === 'ko' ? (
              	<ZiggleKoreanLogo className="h-15 md:w-auto" />
              ) : (
                <ZiggleEnglishLogo className="h-15 md:w-auto" />
              )}
```

2023-11-17 15:39 UTC, MiRoro2 commented
일단 이렇게 가고 다중언어는 나중에 지원하는 게 어떤가요

2023-11-17 15:45 UTC, 2paperstar approved these changes

2023-11-17 15:45 UTC, 2paperstar commented
> 일단 이렇게 가고 다중언어는 나중에 지원하는 게 어떤가요

좋습니다

2023-11-18 01:05 UTC, MiRoro2 commented on src/app/components/templates/Navbar/Navbar.tsx
> +              )}
피드백 반영했습니다!

2023-11-18 01:07 UTC, merged