mypage api connection
gsainfoteam/ziggle-fe pull request #140
Opened 2023-11-18 19:30 UTC by no-ikjun

2023-11-18 19:32 UTC, 2paperstar approved these changes
코멘트만 봐주십셔

2023-11-18 19:32 UTC, 2paperstar commented on src/api/auth/auth.ts
> +};
logout은 그렇다쳐도 withdraw는 api 폴더에 있으면 좀 이상한데요..? 이 함수는 MypageProfile 컴포넌트쪽으로 빼야할듯

2023-11-18 19:34 UTC, 2paperstar requested changes

2023-11-18 19:34 UTC, 2paperstar commented on src/app/[lng]/mypage/page.tsx
> +  ).list;
own이 안 먹는게 getAllNotices 쓸 때 유저 정보가 같이 안 넘어가서 그래요. 이건 이 PR에서 수정해주세요.

2023-11-19 02:35 UTC, no-ikjun commented on src/app/[lng]/mypage/page.tsx
> +  ).list;
?? 이거 어케 넘겨줘요? API에 없는 것 같은데

2023-11-19 02:36 UTC, 2paperstar commented on src/app/[lng]/mypage/page.tsx
> +  ).list;
쿠키에서 토큰 빼서 authorization 헤더에 bearer 토큰으로

2023-11-19 03:09 UTC, 2paperstar requested changes

2023-11-19 03:09 UTC, 2paperstar commented on src/api/notice/notice.ts
> +        Authorization: `Bearer ${cookieStore.get('access_token')}`,
.value

2023-11-19 16:41 UTC, 2paperstar approved these changes

2023-11-19 16:41 UTC, merged