222 feature change zabo component UI
gsainfoteam/ziggle-fe pull request #224
Opened 2024-03-13 12:16 UTC by dohyun-ko

2024-03-18 02:03 UTC, 2paperstar requested changes

2024-03-18 02:03 UTC, 2paperstar commented on src/app/components/organisms/Zabo/ZaboTags.tsx
> +        <a
Link 컴포넌트

2024-03-20 06:10 UTC, dohyun-ko commented on src/app/components/organisms/Zabo/Zabo.tsx
> +dayjs.extend(relativeTime);
이건 initClient로 빼면 사용이 불가능하네요... 그냥 냅뒀습니다.

2024-03-20 06:13 UTC, 2paperstar commented on src/app/components/organisms/Zabo/Zabo.tsx
> +dayjs.extend(relativeTime);
InitClient말고 initDayjs 파일 있어요!!! 거기에서 해주시면 돼요

2024-03-20 06:13 UTC, 2paperstar commented
빌드 에러도 해결해주세요

2024-03-20 10:52 UTC, 2paperstar approved these changes
![image](https://github.com/gsainfoteam/ziggle-fe/assets/125528915/66a53f03-fb9a-4d9a-a524-0b971a7cc3a7)

2024-03-21 00:10 UTC, merged