223 feature change navbar UI to web v3 design
gsainfoteam/ziggle-fe pull request #229
Opened 2024-03-27 06:01 UTC by ParkJumyung

2024-03-27 16:26 UTC, ParkJumyung commented on src/app/components/molecules/searchBar/SearchBar.tsx
> +          isExpanded ? 'stroke-greyDark' : 'stroke-black'
svg의 stroke color가 안 바뀌는데 왜 그런지 모르겠어요;;;;

2024-03-27 16:27 UTC, ParkJumyung commented on src/app/components/templates/Navbar/Navbar.tsx
> +            <ZiggleCompactLogo className="h-[31px] md:hidden" />
logo 의 g 밑 부분이 살짝 짤리는데 왜 그런지 모르겠어요;;

2024-03-27 16:35 UTC, 2paperstar commented on src/app/components/templates/Navbar/Navbar.tsx
> +            <ZiggleCompactLogo className="h-[31px] md:hidden" />
음.. 🤔

2024-03-27 16:35 UTC, 2paperstar commented on src/app/components/molecules/searchBar/SearchBar.tsx
> +          isExpanded ? 'stroke-greyDark' : 'stroke-black'
저게 svg안에서 아예 값이 픽스 되어있으면 못 바꿔요

2024-03-28 02:31 UTC, 2paperstar requested changes

2024-03-28 02:31 UTC, 2paperstar commented on src/app/components/templates/Navbar/Navbar.tsx
> +  let user = await auth();
const

2024-03-28 02:31 UTC, 2paperstar commented on tailwind.config.ts
> +        black: '#252525',
피그마에 정의된 컬러 이름이 `black`인가요?

2024-03-28 04:17 UTC, ParkJumyung commented on tailwind.config.ts
> +        black: '#252525',
넴

2024-03-28 04:19 UTC, 2paperstar commented on tailwind.config.ts
> +        black: '#252525',
흠... 원래 tailwind에서 black은 `#000000`일거라 충돌이 일어나는건 아닐지 걱정 되네요

2024-03-28 04:22 UTC, ParkJumyung commented on tailwind.config.ts
> +        black: '#252525',
text가 같은 색이라서 black을 없애도 될 것 같네요!

2024-03-28 04:24 UTC, 2paperstar requested changes

2024-03-28 04:24 UTC, 2paperstar commented on src/app/components/templates/Navbar/Navbar.tsx
> +    <header className="flex h-[50px] w-full items-center justify-between bg-white py-0 pl-[8px] pr-[5px] text-black md:px-[16px] md:py-[8px]">
header 같은 컨테이너는 높이를 디자인에 따라 가지말고, 여백만 설정을 해둔 다음에 콘텐츠의 크기에 따라 변할 수 있게 해주세요
여백도 px단위가 아닌 pl-2 처럼 사용해서 rem 단위를 쓸 수 있게 해주세요

2024-04-27 15:01 UTC, 2paperstar approved these changes
굿이에요 굿~~

2024-04-28 03:46 UTC, merged