230 feature change serach result page to v3 design
gsainfoteam/ziggle-fe pull request #234
Opened 2024-04-28 15:05 UTC by ParkJumyung

2024-05-08 06:09 UTC, MiRoro2 commented
완전 잘 구현해주셨어요

2024-05-08 06:10 UTC, MiRoro2 commented on src/app/i18next/locales/en/translation.json
> +    "timeLeft": "{{timeLeft}} left",
<img width="264" alt="스크린샷 2024-05-08 오후 3 06 16" src="https://github.com/gsainfoteam/ziggle-fe/assets/57053429/ee1763e7-dcc7-4796-a890-0e5363f029f1">
얘가 왜 이러는지 한 번 살펴봐야 할 것 같긴 하네요

2024-05-08 06:13 UTC, MiRoro2 commented on src/app/globals.css
> -@media (prefers-color-scheme: dark) {
이거는 디버깅용으로 변경하신건가요..? 저는 시스템이 light인데 실행하니까 dark로 뜨더라구요

2024-05-08 06:22 UTC, MiRoro2 commented on src/app/i18next/locales/en/translation.json
> +    "timeLeft": "{{timeLeft}} left",
![image](https://github.com/gsainfoteam/ziggle-fe/assets/57053429/e3634e5c-1f90-4c4a-b228-bc3bc8b7a936)

아마 이런 형식으로 써야 하지 않나 싶네요

2024-05-08 06:42 UTC, MiRoro2 commented on src/app/components/molecules/Pagination/Pagination.tsx
> +        <div className="text-xl">of</div> {/*TODO: Translate? */}
translate (제 개인적인 의견으로는) 안 해도 될 것 같아요 👍

2024-05-08 06:51 UTC, MiRoro2 commented on src/app/components/organisms/Zabo/ZaboActions.tsx
아 원래 이 부분에 액션이 안 붙어있었는데 붙여주셨군요

2024-05-08 06:55 UTC, MiRoro2 commented on src/app/components/organisms/Zabo/ZaboActions.tsx
> +        <Fire width={36} className="h-7 w-7 hover:fill-primary md:h-9 md:w-9" />
호버링 이펙트..... 임팩트 있는 걸로 하나 만들게요..... 🥲

2024-05-08 06:56 UTC, MiRoro2 commented on src/app/components/organisms/Zabo/ZaboActions.tsx
notice reaction에 대해 확장성 있게 코드를 짜주신 점이 정말 인상적이네요 
나중에 ZaboAction에 다른 이모지를 추가할 때 쉽게 추가할 수 있을 것 같네요

2024-05-08 06:59 UTC, MiRoro2 commented on src/app/components/templates/ResultZabo/ResultTextZabo.tsx
> +        <div className="line-clamp-4 text-ellipsis text-start text-sm font-medium">
```suggestion
        <div className="line-clamp-4 text-ellipsis text-start font-medium">
```
레귤러로 바꾸는 게 나을것같아요 sm은 너무 작아서..

2024-05-08 07:00 UTC, MiRoro2 commented on tailwind.config.ts
> +  plugins: [require('tailwind-scrollbar')({ nocompatible: true })],
👀 @2paperstar

2024-05-08 11:44 UTC, ParkJumyung commented on src/app/globals.css
> -@media (prefers-color-scheme: dark) {
하얀 배경 확인해 보려고 잠깐 바꿨는데 그대로 올라갔네요;;

2024-05-08 11:44 UTC, ParkJumyung commented on src/app/components/templates/ResultZabo/ResultImageZabo.tsx
> +const ResultImageZabo = async (props: ResultZaboProps) => {
맨 아랫 부분에 ZaboActions에 props전체를 전달해주어야 해서 props로 받고 나서 따로 분해했어요

2024-05-08 11:45 UTC, ParkJumyung commented on src/app/components/templates/Navbar/Navbar.tsx
> +          href={user ? `/mypage` : `/login`}
붙이니까 http://localhost:3000/en/en/login으로 가서 404뜨던데요...?

2024-05-08 11:46 UTC, ParkJumyung commented on tailwind.config.ts
> +  plugins: [require('tailwind-scrollbar')({ nocompatible: true })],
resultImageZabo에서 이미지 많을 때 횡스크롤바 스타일링때문에 만졌는데 잘 모르겠네요...
로컬이랑 프리뷰랑 스크롤바 스타일링이 좀 다른 것 같기도 하구요...

2024-05-08 12:18 UTC, 2paperstar requested changes

2024-05-08 12:18 UTC, 2paperstar commented on src/app/components/molecules/Pagination/Pagination.tsx
> +          ${Math.min((page + 1) * itemsPerPage, items)}`}
구두로 말한대로 한줄로 써지면 좋겠어요

2024-05-08 12:18 UTC, 2paperstar commented on tailwind.config.ts
> +  plugins: [require('tailwind-scrollbar')({ nocompatible: true })],
문서 찾아보니까 커스텀 스타일링이 더 필요할 때 저걸 사용한다고 하는 것 같네요

2024-05-08 12:18 UTC, 2paperstar commented on src/app/components/organisms/Zabo/ZaboActions.tsx
> +    if (fireReaction) {
여기에 isReacted 붙어야 되는거 아닌가요? 밑에도 마찬가지

2024-05-09 00:24 UTC, MiRoro2 approved these changes
LVGTM

2024-05-09 00:27 UTC, 2paperstar approved these changes

2024-05-09 04:34 UTC, merged