resized components
gsainfoteam/ziggle-fe pull request #24
Opened 2023-07-12 12:15 UTC by MiRoro2

컴포넌트들 전체적으로 리사이징하고 
디렉토리 구조 도현이가 한거에 맞춰서 조금 변경했습니다 
(각 페이지에 들어가는 컴포넌트들은 그 페이지 안 폴더 안에만 넣어놓는 구조로)

+로고, 배너 수정

2023-07-13 04:07 UTC, 2paperstar requested changes

2023-07-13 04:07 UTC, 2paperstar commented on src/pages/home/Banner.tsx
>  interface BannerProps {}
캐러셀로 만들기 위한 프롭인가요?

2023-07-13 04:07 UTC, 2paperstar commented on src/pages/myPage/myPage.tsx
>  const myPage = () => {
반응형이 좀 필요할 것 같아요

2023-07-13 04:07 UTC, 2paperstar commented on src/templates/navbar/Navbar.tsx
> +      </div>
Link 컴포넌트 사용해서 감싸주세요 (시멘틱 살리기)

2023-07-13 04:07 UTC, 2paperstar commented on src/templates/navbar/Navbar.tsx
> +          >
윗 리뷰 댓글과 동일

2023-07-13 09:35 UTC, MiRoro2 commented on src/molecules/search/Search.tsx
> +          }}
X버튼에 넣을려고 했는데 왜 저게 저기들어가있지
미스테리군

2023-07-13 09:36 UTC, MiRoro2 commented on src/molecules/search/Search.tsx
> +
뺌

2023-07-13 09:37 UTC, MiRoro2 commented on src/pages/myPage/myPage.tsx
>  const myPage = () => {
텍스트 길이에 따라 ellipsis를 준다던가 데이터 개수에 따라 다르게 보인다던가 하는거..는...
그래 내가 해야겠지
그냥 제가 할게요 @Shimsuyeon

2023-07-13 09:39 UTC, MiRoro2 commented on src/pages/home/Banner.tsx
>  interface BannerProps {}
도현이의 유산임
![image](https://github.com/gsainfoteam/ziggle-fe/assets/57053429/b2d1cda7-5310-4f6c-9bc1-814659a84736)

2023-07-13 10:22 UTC, Shimsuyeon commented on src/pages/myPage/myPage.tsx
>  const myPage = () => {
엇

2023-07-13 10:23 UTC, MiRoro2 commented on src/pages/myPage/myPage.tsx
>  const myPage = () => {
지금 바쁘시..죠??ㅠㅠ @Shimsuyeon

2023-07-13 10:43 UTC, Shimsuyeon commented on src/pages/myPage/myPage.tsx
>  const myPage = () => {
지금 당장은 어려운데 제가 10시쯤 퇴근해서 그때 볼 수 있을 것 같아요 혹시 바로 고쳐야 하나요?

2023-07-17 05:40 UTC, MiRoro2 commented on src/pages/myPage/myPage.tsx
>  const myPage = () => {
@Shimsuyeon 필요사항들 issue로 따로 남겨두었습니다

2023-07-17 05:42 UTC, MiRoro2 commented
@2paperstar 재리뷰 부탁드립미다
@dohyun-ko 리뷰플리즈

2023-07-17 05:58 UTC, dohyun-ko approved these changes

2023-07-17 05:58 UTC, dohyun-ko commented on src/atoms/containers/content/Content.tsx
> +const CONTENT_AREA_DESKTOP = `calc(100% - 2 * ${defaults.pageSideGap})`;
좋아요

2023-07-17 05:58 UTC, dohyun-ko commented on src/atoms/figures/circle/Circle.tsx
> +  border?: [React.CSSProperties["width"], React.CSSProperties["color"]];
```suggestion
  border?: React.CSSProperties["border"];
```
이렇게 하는 건 어떤가요?

2023-07-17 05:58 UTC, dohyun-ko commented on src/atoms/filledArrow/FilledArrowBtn.tsx
> +  }
switch문 좋은데 AnimatedBtn 안쪽으로 집어넣으면 더 깔끔할 것 같아요
```suggestion

  return (
    <AnimatedBtn onClick={onClick}>
    {
      (() => {
        switch (direction) {
          case HorizontalDirection.LEFT:
              // Left
              return isPrimary ? <Icon.ArrowCircleLeftPrimaryFilled width={width} height={height} /> : <Icon.ArrowCircleLeftDeselectedFilled width={width} height={height} />
              
                case HorizontalDirection.RIGHT:
                   return isPrimary ? <Icon.ArrowCircleRightPrimaryFilled width={width} height={height} /> ? <Icon.ArrowCircleRightDeselectedFilled width={width} height={height} />
          } 
       })()
    }
    </AnimatedBtn>
  )
```

2023-07-17 05:58 UTC, dohyun-ko commented on src/atoms/imageRenderer/ImageRenderer.tsx
tGP와 tMS에 대한 설명이 있거나 직관적인 이름으로 바꾸면 좋을 듯 해요

2023-07-17 05:58 UTC, dohyun-ko commented on src/pages/home/assets/banner1.png
LGTM 👍

2023-07-17 05:58 UTC, dohyun-ko commented on src/pages/searchPage/assets/Search.gif
굉장해요

2023-07-17 05:58 UTC, dohyun-ko commented on src/pages/searchPage/searchPage.tsx
p태그 중첩 없애야 해요

2023-07-17 07:53 UTC, 2paperstar approved these changes
LGTM 👍

리뷰어 목록에서 새로고침 눌러서 리뷰 재요청 해주시면 됩니당..!

2023-07-17 07:53 UTC, 2paperstar commented on src/atoms/filledArrow/FilledArrowBtn.tsx
> +};
```suggestion
const icons = {
  [HorizontalDirection.LEFT]: {
    primary: Icon.ArrowCircleLeftPrimaryFilled,
    deselected: Icon.ArrowCircleLeftDeselectedFilled,
  },
  [HorizontalDirection.RIGHT]: {
    primary: Icon.ArrowCircleRightPrimaryFilled,
    deselected: Icon.ArrowCircleRightDeselectedFilled,
  },
};

const FilledArrowBtn = ({
  isPrimary,
  direction,
  width,
  height,
  onClick,
}: FilledArrowBtnProps) => {
  const Icon = isPrimary
    ? icons[direction].primary
    : icons[direction].deselected;
  return (
    <AnimatedBtn onClick={onClick}>
      <Icon width={width} height={height} />
    </AnimatedBtn>
  );
};
```

이렇게는 어떨까요?

2023-07-17 07:53 UTC, 2paperstar commented on src/index.css
> +}
혹시 globalStyles.ts만 바꿔서는 적용이 안 됐나요?

2023-07-17 07:53 UTC, 2paperstar commented on src/pages/home/Banner.tsx
> +// interface BannerProps {}
나중에 코드 전체적으로 주석 정리가 필요할 듯 하네요

2023-07-17 07:53 UTC, 2paperstar commented on src/pages/searchPage/CloseBtnAnimation.tsx
> +`;
재사용 안하면 그냥 한번에 작성해도 좋을 것 같아요
```suggestion
const AnimationWrapper = styled.div`
  animation: ${fadeInWithGoRight} 0.5 cubic-bezier(0, 0.51, 0.38, 1);
`;
```

2023-07-17 07:53 UTC, 2paperstar commented on src/pages/searchPage/SearchBarAnimation.tsx
> +`;
동일

2023-07-17 07:53 UTC, 2paperstar commented on src/pages/searchPage/assets/Search.gif
오.. 혹시 이런 애니메이션이 많아질 것 같으면 lottie 도입을 고려하는건 어떨까요?!

2023-07-17 07:53 UTC, 2paperstar commented on src/pages/searchPage/SearchGif.tsx
> +    </>
불필요한 fragment..?

2023-07-17 07:53 UTC, 2paperstar commented on src/templates/navbar/Navbar.tsx
> +      <Link to={"/"}>
```suggestion
      <Link to="/">
```
이렇게 적어도 됩니다

2023-07-17 07:53 UTC, 2paperstar commented on src/types/types.ts
> +  tMS?: number; // the minimum share
윗쪽에 댓글도 있긴한데, 이정도면 그냥 풀 네임으로 적어도 될 것 같아요

2023-07-17 07:53 UTC, 2paperstar commented on src/atoms/figures/circle/Circle.tsx
> +  border?: [React.CSSProperties["width"], React.CSSProperties["color"]];
box-shadow 말고 border 속성을 사용한 다음에, box-sizing을 border-box로 주면 될 것 같아요

2023-07-19 11:33 UTC, MiRoro2 commented on src/atoms/figures/circle/Circle.tsx
> +  border?: [React.CSSProperties["width"], React.CSSProperties["color"]];
와
CSS까지 마스터한 보성 그는 대체...

2023-07-19 11:38 UTC, MiRoro2 commented on src/pages/searchPage/assets/Search.gif
Lottie 저도 하려고 했으나... 본인은 애프터 이펙트에 Bodymovin 플러그인 추가 불가 이슈로 ㅠㅠ
혹시 보성이 가능? 저 저거 만든 aep 파일 있음

2023-07-19 11:42 UTC, MiRoro2 commented on src/index.css
> +}
저게 왜 들어갔을까
지울게요

2023-07-19 11:43 UTC, MiRoro2 commented on src/pages/searchPage/SearchGif.tsx
> +    </>
헉스

2023-07-19 11:43 UTC, MiRoro2 commented on src/pages/searchPage/CloseBtnAnimation.tsx
> +`;
음 확실히 그럴것같네요

2023-07-19 11:45 UTC, MiRoro2 commented on src/atoms/filledArrow/FilledArrowBtn.tsx
> +};
좀 더 똑똑한 방식이네요
굿굿 다음 이슈에 리팩터링 todo로 넣었습니다

2023-07-19 11:45 UTC, merged

2023-07-19 11:46 UTC, MiRoro2 commented
https://github.com/gsainfoteam/ziggle-fe/issues/26#issue-1807024521

2023-07-19 12:14 UTC, cra1nbow commented on src/pages/searchPage/assets/Search.gif
저 가능해요

2023-07-19 12:14 UTC, 2paperstar commented on src/pages/searchPage/assets/Search.gif
저 가능해요