238 feature v3 connect writing page apis
gsainfoteam/ziggle-fe pull request #245
Opened 2024-05-08 10:49 UTC by dohyun-ko

다행히 UI를 변경할 때 api 로직은 유지되어 수정할 내용이 없었습니다.
모바일 화면에 맞게 반응형 작업을 하였습니다.
idp 로그인이 불가능해 아직 글 작성 테스트는 하지 못했습니다.

2024-05-11 06:51 UTC, MiRoro2 commented
- idp 로그인이 불가능한게 디버깅에서 크리티컬한 이슈네요.. 다른 것보다 이 사안이 가장 급하게 해결해야 할 이슈 같아요

- 자동 저장 기능의 경우 완벽히 잘 작동하는 것 같아요
- 다만 제가 구현한 디자인에서는 사용자 입력을 기반으로 디바운스될 때마다 저장하는 것으로 기획하긴 했었는데, 혹시 이 구현에 어려움이 있어서 3초마다 저장되는 방식으로 채택하신 건가요?

2024-05-11 06:52 UTC, MiRoro2 commented on src/app/[lng]/(common)/write/AttachedPhoto.tsx
> +const AttachedPhoto = ({ src, onDeleteClick }: ImagePreviewItemProps) => {
영어 이슈 🥲

2024-05-12 02:20 UTC, MiRoro2 commented on src/app/[lng]/(common)/write/page.tsx
현재 모바일 뷰로 봤을 때 x축으로 overflow가 일어나는 현상이 있습니다.. 한번 봐주시면 좋을것같아요

2024-05-12 02:21 UTC, MiRoro2 commented on src/app/[lng]/(common)/write/TagInput.tsx
taginput 왼쪽 padding을 쪼큼만 키워주시면 좋을것같아요

2024-05-12 02:22 UTC, MiRoro2 commented on src/app/[lng]/(common)/write/AttachedPhoto.tsx
혹시 Attathced Photo 가장자리에 round 넣어주실 수 있나욥

2024-05-12 02:24 UTC, MiRoro2 commented on src/app/components/templates/ZaboCarousel/ZaboCarousel.tsx
여기서도 지워졌었구나 👀 
여러 브랜치에서 지워지는 ZaboCarousel

2024-05-12 02:24 UTC, MiRoro2 requested changes
도현짱짱맨

2024-05-18 16:02 UTC, dohyun-ko commented on .yarn/cache/next-npm-14.0.3-45132b65cd-bf53e597b4.zip.br7kjw
몰라요

2024-05-18 16:04 UTC, 2paperstar commented on .yarn/cache/next-npm-14.0.3-45132b65cd-bf53e597b4.zip.br7kjw
지워도 될 것 갈은 파일인데,, .yarn 날리고 다시 install 해서 푸시해주세용

2024-05-19 04:09 UTC, 2paperstar requested changes

2024-05-19 04:09 UTC, 2paperstar commented on src/app/[lng]/(common)/write/page.tsx
> +    const interval = setInterval(() => {
1. 주석과 실제가 맞지 않습니다
2. https://www.tiny.cloud/docs-4x/advanced/events/#change
해당 이벤트를 활용한다면 debounce, 또는 throttle 방식으로 구현이 가능할 것 같아요

2024-05-21 07:09 UTC, 2paperstar approved these changes

2024-05-21 07:30 UTC, MiRoro2 approved these changes
LGTM

2024-05-21 07:52 UTC, merged