257 feature add notice modify
gsainfoteam/ziggle-fe pull request #266
Opened 2024-05-22 14:32 UTC by dohyun-ko

공지 수정 & 영어공지 추가 & 추가공지 기능 넣었습니다.

코드가 더러울 수 있습니다... 최선을 다했습니다.

2024-05-22 17:09 UTC, 2paperstar requested changes

2024-05-22 17:09 UTC, 2paperstar commented on src/app/[lng]/(common)/(common)/mypage/page.tsx
> +            id={userData?.uuid ?? ''}
엥..? 이러면 uuid가 보이는거 아니에요?

2024-05-22 17:09 UTC, 2paperstar commented on src/app/[lng]/(common)/(needSidebar)/notice/[id]/AuthorActions.tsx
> +            console.log(e);
지우기

2024-05-22 17:09 UTC, 2paperstar commented on src/app/[lng]/(common)/(needSidebar)/notice/[id]/NoticeInfo.tsx
> +        <AuthorActions noticeId={Number(id)} lng={lng} />
id가 number가 아니에요?

2024-05-22 17:09 UTC, 2paperstar commented on src/app/[lng]/(write)/write/NoticeTypeSelector.tsx
>                  type: noticeType,
```suggestion
            onClick={!disabled && () => {
              setNoticeType(noticeType);
              sendLog(LogEvents.noticeWritingPageSetType, {
                type: noticeType,
```

2024-05-22 17:09 UTC, 2paperstar commented on src/app/api/notice/[noticeId]/additional/route.ts
> +  console.log(body);
지우기

2024-05-22 17:09 UTC, 2paperstar commented on src/app/[lng]/(write)/write/NoticeEditor.tsx
good practice

2024-05-22 17:09 UTC, 2paperstar commented on src/utils/utils.ts
> +export const calculateTimeRemaining = (createdAt: Dayjs) => {
```suggestion
export const calculateRemainingTime = (createdAt: Dayjs) => {
```

2024-05-22 17:09 UTC, 2paperstar commented on src/utils/utils.ts
> +    .diff(currentTime, 'second');
```suggestion
  const editingLimit = dayjs(createdAt).add(14, 'minutes').add(50, 'seconds');
  const diffInSeconds = editingLimit.diff(currentTime, 'second');
```

server side에서는 Dayjs 객체를 프롭으로 넘길 수 없기 때문에 string으로 전달이 됩니다
dayjs.Dayjs | string으로 타입을 다 받아서 dayjs로 한번 래핑해주는게 좋습니당

2024-05-23 00:49 UTC, dohyun-ko commented on src/app/[lng]/(common)/(common)/mypage/page.tsx
> +            id={userData?.uuid ?? ''}
아아 studentNumber라고 써야하는데 실수했네요

2024-05-23 00:50 UTC, dohyun-ko commented on src/app/[lng]/(common)/(needSidebar)/notice/[id]/NoticeInfo.tsx
> +        <AuthorActions noticeId={Number(id)} lng={lng} />
헉실수

2024-05-23 00:52 UTC, dohyun-ko commented on src/app/[lng]/(write)/write/NoticeTypeSelector.tsx
>                  type: noticeType,
boolean is not assignable to onclick...

2024-05-23 00:53 UTC, dohyun-ko commented on src/utils/utils.ts
> +    .diff(currentTime, 'second');
와우 그래서였군요

2024-05-23 02:19 UTC, 2paperstar approved these changes
good

2024-05-23 03:41 UTC, merged