:sparkles: Add notice writing page
gsainfoteam/ziggle-fe pull request #27
Opened 2023-07-18 14:17 UTC by dohyun-ko

2023-07-19 13:46 UTC, 2paperstar requested changes
머지하면서 에러 뜬 부분이 있네요! 확인해주세요 :)

2023-07-19 13:52 UTC, 2paperstar commented
https://www.tiny.cloud/docs/tinymce/6/react-pm-bundle/
tinymce 관련해서 찾아보니까 직접 빌드해서 쓰진 말라고 그러는데 왜 공식문서에서 이렇게까지 말리는건지 궁금하네요

2023-07-25 15:13 UTC, dohyun-ko commented
> https://www.tiny.cloud/docs/tinymce/6/react-pm-bundle/ tinymce 관련해서 찾아보니까 직접 빌드해서 쓰진 말라고 그러는데 왜 공식문서에서 이렇게까지 말리는건지 궁금하네요

그럼 tinymce를 백엔드에 띄우는게 좋으려나요 회의 때 얘기해보죠

2023-07-25 15:45 UTC, 2paperstar commented
@dohyun-ko 파일이름 대소문자가 달라서 에러가 하나 더 있었네요! 커밋해두었습니다 :)

2023-07-25 15:53 UTC, cra1nbow commented on src/pages/noticeWriting/NoticeWritingImageInput.tsx
> +import ImagePreviewItem from "./ImagePreviewItem";
import sorting이 안 되어있습니다

2023-07-25 15:56 UTC, cra1nbow commented on src/pages/noticeWriting/TagSelector.tsx
> +              setTags([...tags, ...tag.split(" ").filter((t) => t !== "")]);
중복된 태그 입력도 막아주세요! 그렇지 않으면 duplicate key 에러가 발생합니다(L34)

2023-07-25 16:03 UTC, cra1nbow commented on src/pages/noticeWriting/NoticeWriting.tsx
> +  const [deadline, setDeadline] = useState<string>(dateFormat(new Date(), "-"));
날짜 다룰 일이 전반적으로 많을텐데, dayjs 등 날짜 라이브러리를 사용하는건 어떨까요?

2023-07-25 16:04 UTC, cra1nbow commented on src/pages/noticeWriting/NoticeWriting.tsx
> +            tinymceScriptSrc={"../../../tinymce/tinymce.min.js"}
이거 배포 환경에도 적용이 될까요..? 어차피 tinymce 폴더를 public으로 옮긴다음에 /tinymce/tinymce.min.js 로 하는게 안전할 것 같아요

2023-07-25 16:08 UTC, cra1nbow commented on src/pages/noticeWriting/NoticeWriting.tsx
> +  const editorRef = useRef<any>(null);
타입은 Editor["editor"] 또는 tinymce에 있는 Editor 사용하면 될 것 같아요

2023-07-25 16:18 UTC, 2paperstar approved these changes
LGTM 👍
댓글만 참고해주세요!

2023-07-25 16:18 UTC, 2paperstar commented on src/pages/noticeWriting/NoticeWritingImageInput.tsx
> +        }}
이미 위에서 스타일 지정했어요

2023-07-25 16:18 UTC, 2paperstar commented on src/pages/noticeWriting/NoticeWritingImageInput.tsx
> +import ImagePreviewItem from "./ImagePreviewItem";
import sorting이 안 되어있습니다

2023-07-25 16:18 UTC, 2paperstar commented on src/pages/noticeWriting/NoticeWriting.tsx
> +            />
date input을 opacity: 0으로 숨겨버리고, 대신 밖에 버튼만 따로 만들어서 showPicker로 date picker가 튀어나오게만 하는건 어떨까요?

2023-07-25 16:18 UTC, 2paperstar commented on src/pages/noticeWriting/ImagePreviewItem.tsx
> +        }}
object-fit: cover를 주면 좋겠습니다.

2023-07-25 16:18 UTC, 2paperstar commented on src/pages/noticeWriting/NoticeWritingImageInput.tsx
> +                key={index}
file을 키로 쓰는게 좋을 것 같아요

2023-07-25 16:18 UTC, 2paperstar commented on src/pages/noticeWriting/NoticeWritingImageInput.tsx
> +          >
흠... 이 컴포넌트가 grid-template-rows가 아니라 grid-auto-rows를 1fr로 주는게 더 간격이 맞을텐데 그러면 Grid 컴포넌트를 좀 수정해야겠네요

2023-07-25 16:18 UTC, 2paperstar commented on src/pages/noticeWriting/NoticeWritingImageInput.tsx
> +              />
😮

2023-07-25 16:18 UTC, 2paperstar commented on src/pages/noticeWriting/TagSelector.tsx
> +              setTags([...tags, ...tag.split(" ").filter((t) => t !== "")]);
중복된 태그 입력도 막아주세요! 그렇지 않으면 duplicate key 에러가 발생합니다(L34)

2023-07-25 16:21 UTC, 2paperstar reviewed
댓글이 좀 빠져서 추가로 작성합니당

2023-07-25 16:21 UTC, 2paperstar commented on src/pages/noticeWriting/NoticeWriting.tsx
> +            tinymceScriptSrc={"../../../tinymce/tinymce.min.js"}
이거 배포 환경에도 적용이 될까요..? 어차피 tinymce 폴더를 public으로 옮긴다음에 /tinymce/tinymce.min.js 로 하는게 안전할 것 같아요

2023-07-25 16:21 UTC, 2paperstar commented on src/pages/noticeWriting/NoticeWriting.tsx
> +  const editorRef = useRef<any>(null);
타입은 Editor['editor'] 나 tinymce에 있는 Editor가져와서 쓰면 됨니다

2023-07-25 16:21 UTC, 2paperstar commented on src/pages/noticeWriting/NoticeWriting.tsx
> +  const [deadline, setDeadline] = useState<string>(dateFormat(new Date(), "-"));
앞으로 날짜 다룰 일 많을텐데 dayjs 같은 날짜 라이브러리를 쓰는게 어떨까요?

2023-07-26 05:57 UTC, merged