[FEATURE, BUGFIX, REFACTOR] 공지 상세 페이지 완료
gsainfoteam/ziggle-fe pull request #32
Opened 2023-08-02 20:35 UTC by MiRoro2

resolve #26

2023-08-03 04:45 UTC, 2paperstar requested changes
댓글이 21개네요,, 수정 요청 몇가지 있습니다!

2023-08-03 04:45 UTC, 2paperstar commented on src/molecules/zaboImage/ZaboImage.tsx
> +}>`
타입 제네릭은 한줄로 쓸 수 있으면 한줄로 쓰는게 좋을 것 같아요. (vscode-styled-components 플러그인에 이슈가 있어요)

https://github.com/styled-components/vscode-styled-components/issues/358

2023-08-03 04:45 UTC, 2paperstar commented on src/pages/detailedNotice/ZaboShowcase.tsx
> +      console.log(hex);
로그 없애기

2023-08-03 04:45 UTC, 2paperstar commented on src/pages/detailedNotice/FullPageImageViewer.tsx
> +    console.log(imageIndex);
로그 없애기

2023-08-03 04:45 UTC, 2paperstar commented on src/pages/detailedNotice/ZaboShowcase.tsx
> +      const hex = rgbToHex([color[0], color[1], color[2]]);
rgbToHex 함수를 만들어 쓰지 말고, prominent를 호출할 때 옵션으로 format: 'hex'를 걸어주면 됩니다. (타입은 as로 강제 캐스팅 하면 될 것 같아요)

https://github.com/luukdv/color.js/#format

2023-08-03 04:45 UTC, 2paperstar commented on src/pages/detailedNotice/ZaboShowcase.tsx
> +            }}
인라인 함수를 안 만들어도 될텐데요..?


```suggestion
            onClick={onShow}
```

2023-08-03 04:45 UTC, 2paperstar commented on src/pages/detailedNotice/NoticeInfo.tsx
> +                // 마감일이 지나지 않았을 때만 표시
오 플러터에는 이게 빠져있던 것 같네요 👍

2023-08-03 04:45 UTC, 2paperstar commented on src/pages/detailedNotice/NoticeContent.tsx
> +  const Doc = parser.parseFromString(cleanedContent, "text/html");
웹이니까 이렇게 파서를 쓸 수 있군용,, 꼭 body태그를 가져와야 할까요? tinyMCE에서 body태그는 안 내보내서 이렇게 안 해도 관찮을 것 같긴한데,,

2023-08-03 04:45 UTC, 2paperstar commented on src/utils/calculateDDay.ts
> +  const parsedDeadline = parse(deadline, "yyyy.MM.dd", new Date());
실제로 API 데이터는 ISO 포맷으로 들어오기 때문에 나중에 고려를 해야합니다

2023-08-03 04:45 UTC, 2paperstar commented on package.json
> +    "date-fns": "^2.30.0",
저는 개인적으로 day.js가 나은 것 같던데,, 메소드 체이닝처럼 되고 모든 결과가 immutable해서 인라인으로 바로 쓰기도 편하더라고요

2023-08-03 04:45 UTC, 2paperstar commented on src/types/types.ts
> +  size_theMinimumShare?: number;
언더바는 지양하는게 좋을 것 같아요. 구분을 짓고 싶다면 object 형태로 하는 것도 좋아보입니다.


```suggestion
  size?: {
    greatestProduct?: number;
    minimumShare?: number;
  };
```

2023-08-03 04:45 UTC, 2paperstar commented on src/atoms/containers/flex/Flex.tsx
> +  flex-wrap: wrap; // default
breaking change네요  
Flex 컴포넌트를 쓰는 다른 뷰에서 문제가 생길 수 있으니까 조심해야 합니다. 전체적으로 보진 않았지만 레이아웃이 의도와 다른 곳은 (혹시나) 없는지 확인이 필요합니다.

2023-08-03 04:45 UTC, 2paperstar commented on src/pages/detailedNotice/ImageCarousel.tsx
> +  };
함수 이름 camelCase로

2023-08-03 04:45 UTC, 2paperstar commented on src/pages/detailedNotice/ImageCarousel.tsx
> +  };
```suggestion
  const scroll = (amount: number) => {
    carouselRef.current?.scrollTo({
      left: carouselRef.current.scrollLeft + amount,
      behavior: "smooth",
    });
  };
```

2023-08-03 04:45 UTC, 2paperstar commented on src/pages/detailedNotice/HowboutThese.tsx
> +const HowboutThese = () => {
HowAboutThese..?

2023-08-03 04:45 UTC, 2paperstar commented on src/pages/detailedNotice/FullPageImageViewer.tsx
> +    setImageIndex((imageIndex) => imageIndex + amount);
저는 Math 함수를 써서 이렇게 하기도 해요


```suggestion
    setImageIndex((imageIndex) => Math.max(0, Math.min(imageIndex + amount, maxIndex)));
```

2023-08-03 04:45 UTC, 2paperstar commented on src/pages/detailedNotice/FullPageImageViewer.tsx
> +  left: 0;
```suggestion
  z-index: 100;
  position: fixed;
  inset: 0;
```

2023-08-03 04:45 UTC, 2paperstar commented on src/pages/detailedNotice/FullPageImageViewer.tsx
> +          <Download size="32px" />
프론트 단에서 구현해줘용..

2023-08-03 04:45 UTC, 2paperstar commented on src/pages/detailedNotice/HowboutThese.tsx
> +    if (observerWidth >= 1600) {
가운데 정렬 해주세요

```suggestion
const MasonryResizer = styled.div<{ observerWidth: number }>`
  margin: 0 auto;
  ${({ observerWidth }) => {
    if (observerWidth >= 1600) {
```

2023-08-03 04:45 UTC, 2paperstar commented on src/pages/detailedNotice/BackToMainBtn.tsx
> +      </Button>
애니메이션 개 머싯어요

2023-08-03 04:45 UTC, 2paperstar commented on src/pages/detailedNotice/DetailedNoticePage.tsx
> +`;
용어가 어려워서 이해가 안 됐네요.

ZaboShowcase의 아랫부분을 크롭, 또는 덮기 위해~ 정도로 코멘트 수정하면 다른 분들이 이해하기 쉬울 것 같습니다

2023-08-03 06:11 UTC, dohyun-ko requested changes

2023-08-03 06:11 UTC, dohyun-ko commented on src/molecules/zaboImage/ZaboImage.tsx
> +          />
```suggestion
          {isLoading ? <SkeletonRenderer width={size} height={size} />
          :
          <HeightOriginIMG
            src={src}
            size={size}
            isHover={isHover}
            shadowColor={colorSet.primary}
            isLoading={isLoading}
            onLoad={handleImageLoad}
            borderRadius="5px"
          />}
```

이러는 게 더 깔끔하고 성능상 나아보여요

2023-08-03 06:11 UTC, dohyun-ko commented on src/pages/detailedNotice/NoticeContent.tsx
> +const ContentShower = styled(Text)`
Text 컴포넌트는 <p> 태그라서 안에 전체 html을 다 넣으면 브라우저가 에러를 낼 거 같아요

2023-08-03 06:11 UTC, dohyun-ko commented on src/pages/searchPage/SearchBarAnimation.tsx
> +  animation: ${fadeInWithGoUp} 0.5s cubic-bezier(0, 0.51, 0.38, 1);
역시 애니메이션 장인

2023-08-03 06:11 UTC, dohyun-ko commented on src/utils/calculateDDay.ts
> +  const parsedDeadline = parse(deadline, "yyyy.MM.dd", new Date());
```suggestion
  const parsedDeadline = new Date(deadline);
```
그냥 이렇게 하면 알아서 Date로 바꿔줄 거 같아요!

2023-08-03 06:14 UTC, 2paperstar commented on src/pages/searchPage/SearchBarAnimation.tsx
> +  animation: ${fadeInWithGoUp} 0.5s cubic-bezier(0, 0.51, 0.38, 1);
크으

2023-08-03 06:15 UTC, 2paperstar commented on src/utils/calculateDDay.ts
> +  const parsedDeadline = parse(deadline, "yyyy.MM.dd", new Date());
고렇네요 역시 자스 짱이다

2023-08-03 08:58 UTC, MiRoro2 commented
뭐가 많은데 천천히 resolve 해보겠습니다 ㄷㄷ

2023-08-03 10:23 UTC, MiRoro2 commented on src/molecules/checkboxWithLabel/CheckboxWithLabel.tsx
> +    </label>
나도 알지만....
어쩔 수 없음 저 애니메이션을 구현하기 위해서는

2023-08-03 11:20 UTC, MiRoro2 commented on package-lock.json
지웠음 굿

2023-08-03 11:20 UTC, MiRoro2 commented on src/molecules/checkboxWithLabel/CheckboxWithLabel.tsx
추가했음 굿

2023-08-03 11:26 UTC, MiRoro2 commented on src/molecules/zaboImage/ZaboImage.tsx
> +}>`
@dohyun-ko 저거 하겠다고 인터페이스 만드는건 좀 그런것같고
@2paperstar 저거 vscode에서 왜 저렇게 뜨나 계속 불편했는데 저거였다니.... 캄사

2023-08-03 11:29 UTC, MiRoro2 commented on src/pages/detailedNotice/ZaboShowcase.tsx
> +      const hex = rgbToHex([color[0], color[1], color[2]]);
와 이런건 어디서 찾는거임
ㄷㄷ

2023-08-03 11:32 UTC, 2paperstar commented on src/molecules/checkboxWithLabel/CheckboxWithLabel.tsx
> +    </label>
cbx inline-svg 이런거 말고 따로 styled component를 생성하면 될 것 같기도..?

2023-08-03 11:37 UTC, MiRoro2 commented on src/pages/detailedNotice/ZaboShowcase.tsx
> +            }}
뭐야 얜 왜 이렇게 들어옴
이래서 코드리뷰가 중요한거지

2023-08-03 11:51 UTC, MiRoro2 commented on src/pages/detailedNotice/NoticeContent.tsx
> +  const Doc = parser.parseFromString(cleanedContent, "text/html");
혹시몰라서 써놓았다가 지워도 되는지 확인안하고 그대로 써놨네요

지워도 되어서 그냥 지웠음 굿

2023-08-03 11:56 UTC, MiRoro2 commented on src/utils/calculateDDay.ts
> +  const parsedDeadline = parse(deadline, "yyyy.MM.dd", new Date());
> 

안됩니다...ㅠㅠ

2023-08-03 11:56 UTC, MiRoro2 commented on src/utils/calculateDDay.ts
> +  const parsedDeadline = parse(deadline, "yyyy.MM.dd", new Date());
@dohyun-ko 저거 안됩니다 ㅠㅠ

2023-08-03 11:57 UTC, 2paperstar commented on src/utils/calculateDDay.ts
> +  const parsedDeadline = parse(deadline, "yyyy.MM.dd", new Date());
2023-08-03T11:57:18.740Z 요렇게 들어옵니당

2023-08-03 11:58 UTC, 2paperstar commented on src/utils/calculateDDay.ts
> +  const parsedDeadline = parse(deadline, "yyyy.MM.dd", new Date());
new Date로 yyyy.MM.dd 형식은 파싱이 되던데 왜 안 되는거지,,?

2023-08-05 06:58 UTC, MiRoro2 commented on package.json
> +    "date-fns": "^2.30.0",
date-fns에서 day.js로 교체후 그에 맞춰 메소드 변경했습니다

2023-08-05 06:59 UTC, MiRoro2 commented on src/types/types.ts
> +  size_theMinimumShare?: number;
이 interface가 쓰이는 컴포넌트 deprecated 되었습니다 이 인터페이스도 deprecated 처리했고 다음 이슈에서 해당 컴포넌트, interface 없애겠습니다

2023-08-05 07:02 UTC, MiRoro2 commented on src/pages/detailedNotice/HowboutThese.tsx
> +const HowboutThese = () => {
ㅋㅋㅋ 표준어로 바꿀게요

2023-08-05 07:05 UTC, MiRoro2 commented on src/pages/detailedNotice/FullPageImageViewer.tsx
> +    setImageIndex((imageIndex) => imageIndex + amount);
깔끔하고 좋네여

2023-08-05 07:15 UTC, MiRoro2 commented on src/pages/detailedNotice/FullPageImageViewer.tsx
> +    setImageIndex((imageIndex) => imageIndex + amount);
배너 체인지 인덱싱에도 적용했습니다

2023-08-05 07:19 UTC, MiRoro2 commented on src/pages/detailedNotice/HowboutThese.tsx
> +    if (observerWidth >= 1600) {
![image](https://github.com/gsainfoteam/ziggle-fe/assets/57053429/9d87e82e-e17c-4aea-9bee-623fd58738fc)
별론듯...?

2023-08-05 07:28 UTC, MiRoro2 commented on src/App.tsx
> +            <Route path="/detailedNotice" element={<DetailedNoticePage />} />
오 좋네여 /notice/:id로 수정했습니다

2023-08-05 07:29 UTC, MiRoro2 commented on src/molecules/checkboxWithLabel/CheckboxWithLabel.tsx
> +  }
이거 보기 싫으시면 그냥 일반 체크박스로 대체할까요? 전 저걸 고칠 자신이 없습니다.

2023-08-05 07:36 UTC, MiRoro2 commented on src/atoms/image/Image.tsx
> +  }}
현재 버그로 Skeleton이 렌더링 안되는 버그가 있는데 함께 resolve 해볼게요

2023-08-05 09:41 UTC, cra1nbow commented on src/pages/detailedNotice/HowboutThese.tsx
> +    if (observerWidth >= 1600) {
흠.. 아니면 간격을 조절할 수 있는 방법이 있을까요

2023-08-05 09:42 UTC, 2paperstar commented on src/pages/detailedNotice/HowboutThese.tsx
> +    if (observerWidth >= 1600) {
아니면 너비를 조절해서 항상 꽉차게끔 하면 좋을 것 같아요. (자보처럼)

2023-08-05 09:46 UTC, MiRoro2 commented on src/pages/detailedNotice/HowboutThese.tsx
> +    if (observerWidth >= 1600) {
근데 개인적으로 너무 꽉차면 보기 힘들던데 이대로 해도 저는 괜찮다고 생각해요

2023-08-06 03:52 UTC, MiRoro2 commented on src/molecules/zaboImage/ZaboImage.tsx
> +          />
@dohyun-ko @2paperstar 
스켈레톤이 왜 안 나오나 했더니, 저 상태로 두면 img가 아예 로딩되지 않아서 onLoad가 영원히 호출되지 않는 일이 발생합니다. 
제가 저번에 했을 때는 로딩 안 되었을 때 display none으로 뒀었는데 이 방법이 통했던 이유가 그거였네요

ImageRenderer 컴포넌트를 Image와 ZaboImage 컴포넌트 두 개로 쪼갤 때 저렇게 리팩토링했었는데 display none 방식으로 수정하겠습니다
근데 display none 마음에 안드는데 뭔가 더 좋은 방법이 있으면 알려주세요

2023-08-06 08:32 UTC, 2paperstar commented on src/molecules/zaboImage/ZaboImage.tsx
> +          />
저 부분만 따로 컴포넌트를 분리하고, 이미지를 programmatically 한 방법으로 불러오는 것도 좋을 것 같습니다.

2023-08-06 10:04 UTC, 2paperstar approved these changes
LGTM

2023-08-06 10:04 UTC, 2paperstar commented on src/utils/getDayOfWeek.ts
> +};
사용하기 위해서 locale 파일 추가 필요

dayjs(date).format('dd')

2023-08-06 10:04 UTC, 2paperstar commented on src/pages/detailedNotice/NoticeContent.tsx
> +const ContentShower = styled(Text)`
styled-components에서 지원하는 as attribute 를 사용하면 해결 가능할 것 같습니다

2023-08-06 10:15 UTC, dohyun-ko approved these changes
잘했어요

2023-08-06 10:17 UTC, merged