380 feature attach client level logger
gsainfoteam/ziggle-fe pull request #388
Opened 2024-11-18 11:36 UTC by dohyun-ko

기존에 analytics와 모바일 analytics를 기반으로 작동하지 않는 부분을 고치고 없는 이벤트를 추가했습니다.

2024-11-18 11:36 UTC, dohyun-ko commented
프로덕션에서만 기록됩니다. 엑셀 문서는 곧 업데이트 해두겠습니다.

2024-11-18 11:57 UTC, dohyun-ko commented on src/app/[lng]/AmplitudeProvider.tsx
> +};
불필요한 state를 만들고 싶지 않아요

2024-11-18 11:58 UTC, dohyun-ko commented on src/api/log/send-log.ts
> +  track(event, properties);
async-await가 아닌데 순차적으로 실행되나요?

2024-11-18 11:58 UTC, dohyun-ko commented on src/app/[lng]/(with-page-layout)/(without-sidebar-layout)/mypage/ClientActions.tsx
> +        </Analytics>
굳이 사용자한테 확인을 받을 필요는 없다고 생각합니다

2024-11-18 11:59 UTC, dohyun-ko commented on src/app/[lng]/(with-page-layout)/(with-sidebar-layout)/notice/[id]/AuthorActions.tsx
> +      </Analytics>
별도의 이슈로 다루고 싶네요. 추가해주실래요?

2024-11-18 12:00 UTC, dohyun-ko commented on src/app/[lng]/write/NoticeEditor.tsx
> +import { bool } from 'prop-types';
제가 실수로 불필요한 라이브러리를 임포트했습니다. 삭제하겠습니다.

2024-11-18 12:00 UTC, dohyun-ko commented on src/app/[lng]/write/NoticeEditor.tsx
> +      notice: noticeToSubmit,
싫어요

2024-11-18 12:00 UTC, dohyun-ko commented on src/app/[lng]/write/NoticeEditor.tsx
> +      });
안할래요

2024-11-19 01:16 UTC, 2paperstar requested changes

2024-11-19 01:16 UTC, 2paperstar commented on src/app/[lng]/write/NoticeEditor.tsx
> +
이게 최선일까요..?
차라리 컨디션 안에 있는것을 밖으로 빼고 그 값을 그대로 쓰는게 깔끔하지 않을까요

2024-11-19 01:46 UTC, 2paperstar approved these changes

2024-11-19 01:57 UTC, dohyun-ko commented on src/app/[lng]/write/NoticeEditor.tsx
> +    });
좋은 지적입니다

2024-11-19 02:12 UTC, merged