:sparkles: Add all notices page
gsainfoteam/ziggle-fe pull request #53
Opened 2023-08-20 06:28 UTC by dohyun-ko

전체 공지 페이지 추가 및
- 각종 UI 버그 수정
- SearchPage 및 SearchResult, SearchResultText를 범용적으로 사용할 수 있도록 padding, margin, 계층 구조 등 변경
- SearchResult 리팩토링 (Text 중첩 문제 해결 등)

2023-08-22 05:56 UTC, MiRoro2 commented on src/atoms/highlight/Highlight.tsx
> +      case Font.Aharoni:
Aharoni 안쓰는데 빼도 괜찮을듯요 나중에?

2023-08-22 06:09 UTC, MiRoro2 commented on src/pages/allNotices/AllNoticesPage.tsx
> +        )}
```suggestion
       <Flex
          gap="10px"
          flexDirection="column"
          style={{
            flexWrap: "nowrap",
          }}
        >
          {data?.list.map((notice) =>
            notice.imageUrl ? (
              <SearchResult
                id={notice.id}
                deadline={notice.deadline}
                title={notice.title}
                author={notice.author}
                tags={notice.tags}
                date={notice.createdAt}
                viewCount={notice.views}
                thumbnailUrl={notice.imageUrl}
                searchQuery={""}
                key={notice.id}
              />
            ) : (
              <SearchResultText
                id={notice.id}
                deadline={notice.deadline}
                title={notice.title}
                author={notice.author}
                tags={notice.tags}
                date={notice.createdAt}
                viewCount={notice.views}
                content={notice.body}
                searchQuery={""}
                thumbnailUrl=""
                key={notice.id}
              />
            ),
          )}
        </Flex>
```

2023-08-22 06:10 UTC, MiRoro2 commented on src/pages/allNotices/AllNoticesPage.tsx
> +          <Pagination
페이지네이션 넘기면 작동안하던데 API 문젤까요

2023-08-22 06:10 UTC, MiRoro2 commented on src/pages/searchPage/SearchPage.tsx
> -    // @ts-ignore
👍👍👍😄😄

2023-08-22 06:16 UTC, MiRoro2 commented on src/pages/searchPage/SearchPage.tsx
Search페이지 전체적으로 리팩토링하셨군요

2023-08-22 06:17 UTC, MiRoro2 commented on src/templates/navbar/Navbar.tsx
> +          <Text color={colorSet.colorless} size="1.0625rem" font={Font.Bold}>
rem px 변환 도입이 시급합니다 ㅠ

2023-08-22 06:19 UTC, MiRoro2 commented on src/templates/searchResultText/SearchResultText.tsx
> +    navigate(Paths.noticeDetail + id);
저도 앞으로는 이걸로 navigation 할게요

2023-08-22 06:19 UTC, MiRoro2 commented on src/templates/searchResultText/SearchResultText.tsx
> +            {/* 여기 HTML 처리 해야할 거 같음 */}
미리보기용으로 원래 텍스트가 나와야하는데 안나오고있죠.. 빨리 처리해야할것같습니다

2023-08-22 06:20 UTC, MiRoro2 commented
전체공지 Flex wrap 부분만 수정하면 LGTM입니다

2023-08-22 07:06 UTC, 2paperstar requested changes

2023-08-22 07:06 UTC, 2paperstar commented on src/molecules/pagination/Pagination.tsx
> +          setPage(Math.min(page + 1, totalItems / itemsPerPage - 1));
Math.ceil

2023-08-22 07:06 UTC, 2paperstar commented on src/pages/allNotices/AllNoticesPage.tsx
> +          <Pagination
관련된 파일에 댓글 달아뒀습니다!

2023-08-22 07:06 UTC, 2paperstar commented on src/templates/navbar/Navbar.tsx
> +          <Text color={colorSet.colorless} size="1.0625rem" font={Font.Bold}>
17px..? 사실 저는 이런 값 나오면 무시하고 16px로 처리하는 편이라,, ㅎㅎ

2023-08-22 07:06 UTC, 2paperstar commented on src/pages/searchPage/SearchPage.tsx
> +              )}
이쪽 flex로 한번 감싸주세요

2023-08-22 07:06 UTC, 2paperstar commented on src/pages/searchPage/SearchPage.tsx
>                      ))} */}
주석 필요없으면 제거!

2023-08-22 07:07 UTC, 2paperstar commented on src/pages/searchPage/SearchPage.tsx
> +              )}
뭐야 이미 해주셨네

2023-08-22 12:55 UTC, dohyun-ko commented on src/templates/searchResultText/SearchResultText.tsx
> +    navigate(Paths.noticeDetail + id);
@2paperstar Link 자체에 스타일이 들어가있어서 사용을 꺼렸는데 고민해봐야겠네요

2023-08-22 13:35 UTC, dohyun-ko commented on src/templates/navbar/Navbar.tsx
> +          <Text color={colorSet.colorless} size="1.0625rem" font={Font.Bold}>
@2paperstar 주체적인 개발자 멋지네요 전 디자인 그대로 따라가는 편이라...

2023-08-23 07:27 UTC, dohyun-ko commented on src/pages/searchPage/SearchPage.tsx
>                      ))} */}
@2paperstar 학사공지를 넣을지 말지 미정이라 남겨뒀습니다

2023-08-23 07:27 UTC, 2paperstar commented on src/pages/searchPage/SearchPage.tsx
>                      ))} */}
아하아하

2023-08-23 07:55 UTC, 2paperstar approved these changes
LGTM

2023-08-23 07:57 UTC, merged